name: "Build and Plan"

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  IMAGE_LIST: ${{ vars.NODE_IMAGE }}
  NODE_VERSION: ${{ vars.NODE_VERSION }}
  REGION: ${{ vars.REGION }}

jobs:
  build-job:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: CI - Build Verify
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.16.x

      - name: Install PNPM
        run: |
          npm install -g pnpm

      - name: Install dependencies
        run: |
          pnpm install

      - name: Run Build
        run: |
          pnpm run build
